name: LocalWire
description: A Hyperlocal news platform

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_html: ^0.9.4
  share: ^0.6.0
  http: any
  shared_preferences: ^0.5.2
  flutter_spinkit: ^3.1.0
  url_launcher: ^5.0.1
  flutter_webview_plugin: ^0.3.5
  dynamic_theme: ^1.0.0
  http_middleware: any
  provider:
  sqflite:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.0

flutter_icons:
  image_path_ios: "assets/final-logo.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Samyak
      fonts:
        - asset: assets/fonts/Samyak-Oriya.ttf
    - family: Lohit
      fonts:
        - asset: assets/fonts/Lohit-Oriya.ttf
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Salsa
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf
    - family: Sarala
      fonts:
        - asset: assets/fonts/Sarala.ttf
    - family: Utkal
      fonts:
        - asset: assets/fonts/utkal.ttf
    - family: Sans
      fonts:
        - asset: assets/fonts/Sans-Regular.ttf
    - family: ananta
      fonts:
        - asset: assets/fonts/ananta.ttf
    - family: baloo
      fonts:
        - asset: assets/fonts/baloo.ttf
    - family: proxima-alt-reg
      fonts:
        - asset: assets/fonts/proxima-reg.otf
    - family: proxima-nova-reg
      fonts:
        - asset: assets/fonts/ProximaNovaReg.ttf
    - family: proxima-nova-bold
      fonts:
        - asset: assets/fonts/Proxima_Nova_Bold.otf      